- hosts: localhost
  vars:
    ssh_keys:
      - { private_key: "id_ed25519", public_key: "id_ed25519.pub" }
      - { private_key: "mchp-key", public_key: "mchp-key.pub" }
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-config.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/node.yml
