- name: Git setup email
  git_config:
    name: user.email
    scope: global
    value: "37317525+englishlayup@users.noreply.github.com"
  tags:
  - git-personal
- name: Git setup name
  git_config:
    name: user.name
    scope: global
    value: "Duc Tran"
  tags:
  - git-personal
