- name: Install required packages for fnm
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - unzip

- name: Download fnm installation script
  ansible.builtin.shell:
    cmd: |
      curl -fsSL https://fnm.vercel.app/install | bash
      source {{ lookup('env', 'HOME') }}/.config/fish/conf.d/fnm.fish
      fnm install --lts
    executable: /usr/bin/fish
