- name: Install packages
  become: true
  apt:
    name: [ "fish", "tmux", "fzf", "xsel", "tldr", "ripgrep", "bat" ]

- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Create symbolic link for batcat as bat in ~/.local/bin
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "{{ ansible_env.HOME }}/.local/bin/bat"
    state: link
