- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0700'
    owner: "{{ lookup('env', 'USER') }}"
  tags:
    - dotfiles
    - install
    - ssh

- name: Install private keys
  ansible.builtin.copy:
    src: "./.ssh/{{ item.private_key }}"
    dest: "~/.ssh/{{ item.private_key }}"
    mode: '0600'
  with_items: "{{ ssh_keys }}"
  tags:
    - dotfiles
    - install
    - ssh

- name: Install public keys
  ansible.builtin.copy:
    src: "./.ssh/{{ item.public_key }}"
    dest: "~/.ssh/{{ item.public_key }}"
    mode: '0644'
  with_items: "{{ ssh_keys }}"
  tags:
    - dotfiles
    - install
    - ssh

- name: Install authorized keys
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/' +  item.public_key) }}"
  with_items:  "{{ ssh_keys }}"
  tags:
    - dotfiles
    - install
    - ssh
