- name: Install zsh
  become: true
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Change shell
  become: true
  shell: chsh -s `which zsh` {{ ansible_user_id }}
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.zsh/plugins/zsh-autosuggestions
  tags: *tags_for_zsh_tasks

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: ~/.zsh/plugins/zsh-syntax-highlighting
  tags: *tags_for_zsh_tasks

- name: Install zsh-z
  ansible.builtin.git:
    repo: 'https://github.com/agkozak/zsh-z'
    dest: ~/.zsh/plugins/zsh-z
  tags: *tags_for_zsh_tasks

- name: Install powerlevel10k theme
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: ~/.zsh/plugins/powerlevel10k
  tags: *tags_for_zsh_tasks
